export const someBands = [
  "Extremoduro",
  "Marea",
  "Nirvana",
  "Metallica",
  "Pink Floyd",
  "Queen",
  "The Beatles",
  "Led Zeppelin",
  "The Rolling Stones",
  "Eminem",
  "Denzel Curry",
  "J Cole",
  "Judas Priest",
];

export const madeForYou = [
  { id: 1, artist: "Judas Priest", album: "Painkiller" },
  { id: 2, artist: "Nirvana", album: "Nevermind" },
  { id: 3, artist: "Metallica", album: "Master of Puppets" },
  { id: 4, artist: "Pink Floyd", album: "The Dark Side of the Moon" },
  { id: 5, artist: "Queen", album: "A Night at the Opera" },
  { id: 6, artist: "The Beatles", album: "Abbey Road" },
  { id: 7, artist: "Led Zeppelin", album: "Led Zeppelin IV" },
  { id: 8, artist: "The Rolling Stones", album: "Sticky Fingers" },
  { id: 9, artist: "Metallica", album: "Ride the Lightning" },
  { id: 10, artist: "Pink Floyd", album: "The Wall" },
];

export const jumpBackIn = [
  { id: 1, artist: "Iron Maiden", album: "The Number of the Beast" },
  { id: 2, artist: "Nirvana", album: "In Utero" },
  { id: 3, artist: "Metallica", album: "…And Justice for All" },
  { id: 4, artist: "Pink Floyd", album: "Animals" },
  { id: 5, artist: "Queen", album: "News of the World" },
  { id: 6, artist: "The Beatles", album: "Let It Be" },
  { id: 7, artist: "Led Zeppelin", album: "Houses of the Holy" },
  { id: 8, artist: "The Rolling Stones", album: "Exile on Main St." },
  { id: 9, artist: "Guns N' Roses", album: "Appetite for Destruction" },
  { id: 10, artist: "Pink Floyd", album: "Meddle" },
];

export const recentlyPlayed = [
  { id: 1, artist: "Iron Maiden", album: "Powerslave" },
  { id: 2, artist: "AC/DC", album: "Highway to Hell" },
  { id: 3, artist: "Black Sabbath", album: "Master of Reality" },
  { id: 5, artist: "Guns N' Roses", album: "Use Your Illusion I" },
  { id: 6, artist: "Aerosmith", album: "Pump" },
  { id: 7, artist: "The Doors", album: "The Doors" },
  { id: 8, artist: "The Who", album: "Quadrophenia" },
  { id: 9, artist: "Rush", album: "2112" },
  { id: 10, artist: "Fleetwood Mac", album: "Tusk" },
  { id: 11, artist: "Santana", album: "Abraxas" },
  { id: 12, artist: "Bob Dylan", album: "Blood on the Tracks" },
  { id: 14, artist: "The Clash", album: "London Calling" },
  { id: 15, artist: "Talking Heads", album: "Remain in Light" },
  { id: 16, artist: "The Police", album: "Synchronicity" },
  { id: 17, artist: "Joy Division", album: "Closer" },
  { id: 18, artist: "Ramones", album: "Rocket to Russia" },
  { id: 19, artist: "Queen", album: "The Game" },
  { id: 20, artist: "Led Zeppelin", album: "Physical Graffiti" },
];

export const hipHop90s = [
  { id: 1, artist: "Nas", album: "Illmatic" },
  { id: 2, artist: "The Notorious B.I.G.", album: "Ready to Die" },
  { id: 3, artist: "2Pac", album: "All Eyez on Me" },
  { id: 4, artist: "Dr. Dre", album: "The Chronic" },
  { id: 5, artist: "Snoop Dogg", album: "Doggystyle" },
  { id: 6, artist: "A Tribe Called Quest", album: "The Low End Theory" },
  { id: 7, artist: "OutKast", album: "ATLiens" },
  { id: 8, artist: "Jay-Z", album: "Reasonable Doubt" },
  { id: 9, artist: "Lauryn Hill", album: "The Miseducation of Lauryn Hill" },
  { id: 10, artist: "Cypress Hill", album: "Black Sunday" },
  { id: 11, artist: "Beastie Boys", album: "Ill Communication" },
  { id: 12, artist: "Gang Starr", album: "Moment of Truth" },
  { id: 13, artist: "DMX", album: "It's Dark and Hell Is Hot" },
];
